#!/usr/bin/env python3
name: atap_quotation_tool

channels:
  - conda-forge
  - defaults
  
dependencies:
  # Try to install everything via conda where possible,
  # makes for simpler and quicker installs
  - python=3.8.13
  - numpy
  - pandas
  - openpyxl
  - matplotlib
  - spacy
  - spacy-model-en_core_web_lg
  - nltk=3.7
  - ipywidgets=8.0.2
  - panel=1.1.1
  - pip
  - pip:
      - pymongo==4.1.1
      - pyexcelerate